version: "2"
services:
  database:
    image: mysql
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
     - "3310:3306"
    volumes:
     - /var/lib/mysql
     - ./database:/docker-entrypoint-initdb.d
  web:
    build: .
    ports:
     - "8888:8080"
    depends_on:
     - database
