web:
  build: .
  ports:
   - "8888:8080"
  volumes:
   - /usr/local/tomcat/webapps
  links:
   - database
database:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD:
  ports:
    - "3310:3306"
  volumes:
    - /var/lib/mysql
